parameters:
    vivait_user.api.user_provider.class: Vivait\UserBundle\Security\ApiKeyUserProvider

services:
    vivait_user.api.user_provider:
        class: "%vivait_user.api.user_provider.class%"
        arguments: [@doctrine.orm.entity_manager]
    vivait_user.api.authenticator:
        class:     Vivait\UserBundle\Security\ApiKeyAuthenticator
        arguments: [@vivait_user.api.user_provider]
