services:
    vivait_user.password_resetting:
        class: Vivait\UserBundle\EventListener\PasswordResettingListener
        arguments: [ @router ]
        tags:
            - { name: kernel.event_subscriber }

    vivait_user.two_factor_generator:
        class: Vivait\UserBundle\Form\Type\TwoFactorGeneratorType
        arguments: []
        tags:
          - { name: form.type, alias: 'two_factor_generator' }

    vivait_user.two_factor_cancel:
        class: Vivait\UserBundle\Form\Type\TwoFactorDisableType
        arguments: []
        tags:
          - { name: form.type, alias: 'two_factor_disable' }