vivait_user_security:
    path:     /profile/security
    defaults: { _controller: VivaitUserBundle:Profile:security }

vivait_user_security_two_factor:
    path:     /profile/security/two-factor
    defaults: { _controller: VivaitUserBundle:TwoFactor:twoFactor }

_security_logout:
    path: /logout